$(document).ready(function () {
    var lig = new ListItemGenerator();
    lig.createCategory("Game Saves")
    lig.generateSubList("Your Saves", [{ type: "click", name: "Save #1", link: "#", description: "Game Save #1 Description (Last Loaded: 12/12/2012 15:48)" }, { type: "click", name: "Save #2", link: "#", description: "Game Save #2 Description (Last Loaded: 11/11/2011 14:48)" }, { type: "click", name: "Save #3", link: "#", description: "Game Save #3 Description (Last Loaded: 10/10/2010 13:48)" }, { type: "click", name: "Save #2", link: "#", description: "Game Save #2 Description (Last Loaded: 11/11/2011 14:48)" }, { type: "click", name: "Save #3", link: "#", description: "Game Save #3 Description (Last Loaded: 10/10/2010 13:48)" }, { type: "click", name: "Save #2", link: "#", description: "Game Save #2 Description (Last Loaded: 11/11/2011 14:48)" }, { type: "click", name: "Save #3", link: "#", description: "Game Save #3 Description (Last Loaded: 10/10/2010 13:48)" }, { type: "click", name: "Save #2", link: "#", description: "Game Save #2 Description (Last Loaded: 11/11/2011 14:48)" }, { type: "click", name: "Save #3", link: "#", description: "Game Save #3 Description (Last Loaded: 10/10/2010 13:48)" }, { type: "click", name: "Save #4", link: "#", description: "Game Save #4 Description (Last Loaded: 9/9/2009 12:48)" }, { type: "click", name: "Save #5", link: "#", description: "Game Save #5 Description (Last Loaded: 8/8/2008 11:48)" }, { type: "click", name: "Save #6", link: "#", description: "Game Save #6 Description (Last Loaded: 7/7/2007 10:48)" }, { type: "click", name: "Save #7", link: "#", description: "Game Save #7 Description (Last Loaded: 6/6/2006 09:48)" }, { type: "click", name: "Save #8", link: "#", description: "Game Save #8 Description (Last Loaded: 5/5/2005 08:48)" }], "", "A list of all your saved games!");
    lig.generateSubList("Auto Saves", [{ type: "click", name: "Auto Save #1", link: "#", description: "Auto Save #1 Description (Last Loaded: 12/12/2012 15:36)" }, { type: "click", name: "Auto Save #1", link: "#", description: "Auto Save #1 Description (Last Loaded: 12/12/2012 15:36)" }, { type: "click", name: "Auto Save #1", link: "#", description: "Auto Save #1 Description (Last Loaded: 12/12/2012 15:36)" }, { type: "click", name: "Auto Save #2", link: "#", description: "Auto Save #2 Description (Last Loaded: 11/11/2011 14:36)" }, { type: "click", name: "Auto Save #3", link: "#", description: "Auto Save #3 Description (Last Loaded: 10/10/2010 13:36)" }], "", "A list of all your saved games!");
});

function loadGame(fileName) {
    App.loadSaveGame(fileName);
}
